server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456788
    url: jdbc:mysql://101.132.134.148:3306/zlhz?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.*

logging:
  level:
    com:
      example:
        mapper : debug
